#!/bin/sh
#
# BlackArch Linux Controller Script
#
# Checks environment and does necessary setups.


SUCCESS=0
FAILURE=1

VERBOSE='/dev/null'

# setup qemu-kvm related things
setup_qemu()
{
  return $SUCCESS
}

# setup VMware related things
setup_vmware()
{
  pacman -Syy --needed open-vm-tools > $VERBOSE 2>&1

  systemctl enable vmware-vmblock-fuse > $VERBOSE 2>&1
  systemctl enable vmtoolsd > $VERBOSE 2>&1
  systemctl start vmware-vmblock-fuse > $VERBOSE 2>&1
  systemctl start vmtoolsd > $VERBOSE 2>&1

  return $SUCCESS
}

# setup VirtualBox related things
setup_vbox()
{
  pacman -Syy --needed virtualbox-guest-utils virtualbox-guest-modules-arch > \
    $VERBOSE 2>&1

  systemctl enable vboxservice > $VERBOSE 2>&1
  systemctl start vboxservice > $VERBOSE 2>&1

  return $SUCCESS
}

# are we in a VM? if so, make necessary setups
check_vm_env()
{
  env=$(dmesg |egrep -io 'virtualbox|vmware|qemu' | sort -u)

  if [[ "$env" == *"VirtualBox"* ]]
  then
    setup_vbox
  elif [[ "$env" == "VMware" ]]
  then
    setup_vmware
  elif [[ "$env" == *"QEMU"* ]]
  then
    setup_qemu
  fi

  return $SUCCESS
}

# controller
main()
{
  check_vm_env

  return $SUCCESS
}

# we start here
main
